from snakemake.utils import min_version

min_version('7.14.0')

configfile: 'config/config.yaml'
#container: 'workflow/envs/incura.sif'

ORGANISM = config['organism']

rule all:
    input: 
        'data/fimo_cluster_0/fimo.tsv'

#------------------------------------------------------------------------------------
module getPromoters:
    snakefile: "rules/getPromoters.smk"
    config: config

use rule * from getPromoters

module runFIMO:
    snakefile: "rules/runFIMO.smk"
    config: config

use rule * from runFIMO


# snakemake --profile config/slurm/ ...
