organism: 'Hsapiens'

data:
  url:
    TFs_mm10: 'https://resources.aertslab.org/cistarget/tf_lists/allTFs_mm10.txt'
    TFs_hg38: 'https://resources.aertslab.org/cistarget/tf_lists/allTFs_hg38.txt'
    genome_mm10: 'https://heibox.uni-heidelberg.de/f/de56839fd8b24d0aba4a/?dl=1'
    annot_mm10:
    genome_hg38:
    annot_hg38:

software:
  url:
    meme: 'https://meme-suite.org/meme/meme-software/5.5.7/meme-5.5.7.tar.gz'